services:
  cloud-language-tools:
    image: lucwastiaux/cloud-language-tools:${CLT_TAG}
    environment:
      - DEFAULT_EMAIL
      - GPG_PASSPHRASE
      - CLOUDLANGUAGETOOLS_CORE_KEY
      - ENV
      - GUNICORN_WORKERS
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    network_mode: bridge
    restart: unless-stopped

  scheduled-tasks:
    image: lucwastiaux/cloud-language-tools:${CLT_TAG}
    environment:
      - GPG_PASSPHRASE
      - CLOUDLANGUAGETOOLS_CORE_KEY
      - ENV
      - RUN_SCHEDULED_TASKS=1
    network_mode: bridge
    restart: unless-stopped

  nginx-proxy:
    image: lucwastiaux/nginx-proxy:stable
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html      
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    restart: unless-stopped

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL

volumes:
  certs:
  acme:  
  vhost:
  html: